import { describe, expect, it } from 'vitest';
import { AgentTurnCommitService } from '../src/services/agentTurnCommit.service';
import { AgentDialogueCheckpointService } from '../src/services/agentDialogueCheckpoint.service';

const v2 = { version: 2, kind: 'slot_answer', domain: 'people', objectiveCompleteness: 'unknown', lifecycleCommand: 'none', lifecycleTarget: 'unspecified', lifecycleEvidence: 'unknown', pendingSlotAnswer: 'likely', continuationLike: 'yes', candidateSlotType: 'person', independentObjective: 'no', objectiveType: null, entityHints: ['Lina'], slots: {}, ambiguityFields: [], confidence: .8, source: 'llm' };
function query(row: any) { return { from: () => ({ select: () => ({ eq: function(this: any, key: string, value: unknown) { this[key] = value; return this; }, maybeSingle: async () => ({ data: row, error: null }) }) }) }; }

describe('M-7 durable checkpoint read bindings', () => {
    it('loads exact V2 and preserves sequence/fingerprint', async () => { const result = await new AgentTurnCommitService({ rpc: () => null }, query({ turn_id: 't', actor_user_id: 'a', dialogue_scope_key: 's', turn_sequence: 4, semantic_version: 2, semantic_fingerprint: 'f'.repeat(64), semantic_turn: v2 })).loadSemanticCheckpoint({ turnId: 't', actorUserId: 'a', dialogueScopeKey: 's', turnSequence: 4 }); expect(result.status).toBe('found'); if (result.status === 'found') { expect(result.semanticTurn).toEqual(v2); expect(result.turnSequence).toBe(4); expect(result.fingerprint).toBe('f'.repeat(64)); } });
    it('distinguishes absent checkpoint', async () => { expect((await new AgentTurnCommitService({ rpc: () => null }, query(null)).loadSemanticCheckpoint({ turnId: 't', actorUserId: 'a', dialogueScopeKey: 's' })).status).toBe('not_found'); });
    it.each([{ semantic_version: 1 }, { semantic_version: 9 }])('rejects unsupported semantic version %s', async version => { const result = await new AgentTurnCommitService({ rpc: () => null }, query({ ...version, actor_user_id: 'a', dialogue_scope_key: 's', turn_id: 't', semantic_turn: v2 })).loadSemanticCheckpoint({ turnId: 't', actorUserId: 'a', dialogueScopeKey: 's' }); expect(result.status).toBe('unsupported_version'); });
    it('rejects actor, scope, and sequence mismatch', async () => { const service = new AgentTurnCommitService({ rpc: () => null }, query({ turn_id: 't', actor_user_id: 'a', dialogue_scope_key: 's', turn_sequence: 2, semantic_version: 2, semantic_turn: v2 })); expect((await service.loadSemanticCheckpoint({ turnId: 't', actorUserId: 'other', dialogueScopeKey: 's' })).status).toBe('identity_mismatch'); expect((await service.loadSemanticCheckpoint({ turnId: 't', actorUserId: 'a', dialogueScopeKey: 'other' })).status).toBe('identity_mismatch'); expect((await service.loadSemanticCheckpoint({ turnId: 't', actorUserId: 'a', dialogueScopeKey: 's', turnSequence: 3 })).status).toBe('identity_mismatch'); });
    it('returns invalid for corrupt V2 rather than fabricating', async () => { const result = await new AgentTurnCommitService({ rpc: () => null }, query({ turn_id: 't', actor_user_id: 'a', dialogue_scope_key: 's', semantic_version: 2, semantic_turn: { ...v2, kind: 'bad' } })).loadSemanticCheckpoint({ turnId: 't', actorUserId: 'a', dialogueScopeKey: 's' }); expect(result.status).toBe('invalid'); });
    it('loads active and suspended dialogue without mutating', async () => { const row = { actor_user_id: 'a', dialogue_scope_key: 's', lifecycle: 'active_and_suspended', active_dialogue: { objective: 'a' }, suspended_dialogue: { objective: 'b' }, version: 8, last_applied_turn_id: 't', last_applied_turn_sequence: 7, expires_at: '2030-01-01T00:00:00Z' }; let writes = 0; const result = await new AgentDialogueCheckpointService({ from: () => ({ select: () => ({ eq: function(this: any) { return this; }, maybeSingle: async () => ({ data: row, error: null }) }) }) }).loadDialogueCheckpoint({ actorUserId: 'a', dialogueScopeKey: 's' }); expect(result).toEqual({ status: 'found', expiresAt: row.expires_at, snapshot: { lifecycle: row.lifecycle, activeDialogue: row.active_dialogue, suspendedDialogue: row.suspended_dialogue, version: 8, lastAppliedTurnId: 't', lastAppliedTurnSequence: 7 } }); expect(writes).toBe(0); });
    it('distinguishes empty dialogue and preserves expiry metadata', async () => { const empty = await new AgentDialogueCheckpointService(query(null)).loadDialogueCheckpoint({ actorUserId: 'a', dialogueScopeKey: 's' }); expect(empty.status).toBe('not_found'); const result = await new AgentDialogueCheckpointService(query({ actor_user_id: 'a', dialogue_scope_key: 's', lifecycle: 'active', active_dialogue: {}, suspended_dialogue: null, version: 3, last_applied_turn_id: null, last_applied_turn_sequence: 0, expires_at: '2020-01-01T00:00:00Z' })).loadDialogueCheckpoint({ actorUserId: 'a', dialogueScopeKey: 's' }); expect(result).toMatchObject({ status: 'found', expiresAt: '2020-01-01T00:00:00Z' }); });
    it('uses actor and scope as the only lookup key and never the legacy Map', async () => { let calls = 0; const service = new AgentDialogueCheckpointService({ from: (table: string) => { expect(table).toBe('agent_dialogue_checkpoints'); calls++; return { select: () => ({ eq: function(this: any) { return this; }, maybeSingle: async () => ({ data: null, error: null }) }) }; } }); expect((await service.loadDialogueCheckpoint({ actorUserId: 'a', dialogueScopeKey: 's' })).status).toBe('not_found'); expect(calls).toBe(1); });
});
