import { describe, expect, it, vi } from 'vitest';
import { AgentPersonResolutionService } from '../src/services/agentPersonResolution.service';
import type { NormalizedSemanticTurnV2 } from '../src/types/agentTurnCommit';

const base: NormalizedSemanticTurnV2 = { version: 2, kind: 'slot_answer', domain: 'people', objectiveCompleteness: 'unknown', lifecycleCommand: 'none', lifecycleTarget: 'unspecified', lifecycleEvidence: 'unknown', pendingSlotAnswer: 'likely', continuationLike: 'yes', candidateSlotType: 'person', independentObjective: 'no', objectiveType: null, entityHints: ['Lina'], slots: {}, ambiguityFields: [], confidence: .8, source: 'llm' };
const person = { kind: 'user' as const, id: 'person-1', displayName: 'Lina' };
const dialogue = { lifecycle: 'active', activeDialogue: { objective: 'x' }, suspendedDialogue: null, version: 1, lastAppliedTurnId: null, lastAppliedTurnSequence: 0 };
function service(result: any) { const resolve = vi.fn(async () => result); return { service: new AgentPersonResolutionService({ resolve }), resolve }; }

describe('M-7 SemanticTurn V2 person resolver binding', () => {
    it('translates a pending structured person slot and returns canonical identity', async () => { const x = service({ resolved: person, ambiguous: false, candidates: [person] }); const result = await x.service.resolveFromSemantic({ actorUserId: 'a', dialogueScopeKey: 's', semanticTurn: base, dialogue }); expect(x.resolve).toHaveBeenCalledWith('a', { name: 'Lina' }); expect(result).toEqual({ status: 'resolved', person }); });
    it('preserves zero-match and ambiguous outcomes', async () => { const zero = service({ resolved: null, ambiguous: false, candidates: [] }); expect(await zero.service.resolveFromSemantic({ actorUserId: 'a', dialogueScopeKey: 's', semanticTurn: base, dialogue })).toEqual({ status: 'zero_match' }); const ambiguous = service({ resolved: null, ambiguous: true, candidates: [person] }); expect(await ambiguous.service.resolveFromSemantic({ actorUserId: 'a', dialogueScopeKey: 's', semanticTurn: base, dialogue })).toEqual({ status: 'ambiguous', candidates: [person] }); });
    it.each([{ ...base, candidateSlotType: null }, { ...base, candidateSlotType: 'date_time' }, { ...base, kind: 'read_request', candidateSlotType: null, objectiveType: 'lookup' }])('does not resolve without a structured person candidate', async semanticTurn => { const x = service({ resolved: person, ambiguous: false, candidates: [person] }); expect(await x.service.resolveFromSemantic({ actorUserId: 'a', dialogueScopeKey: 's', semanticTurn, dialogue })).toEqual({ status: 'not_applicable' }); expect(x.resolve).not.toHaveBeenCalled(); });
    it('does not consume an independent read as a pending person answer', async () => { const x = service({ resolved: person, ambiguous: false, candidates: [person] }); const result = await x.service.resolveFromSemantic({ actorUserId: 'a', dialogueScopeKey: 's', semanticTurn: { ...base, kind: 'read_request', candidateSlotType: null, objectiveType: 'lookup', independentObjective: 'yes' }, dialogue }); expect(result.status).toBe('not_applicable'); expect(x.resolve).not.toHaveBeenCalled(); });
    it('can resolve an independent write only when V2 marks a person slot', async () => { const x = service({ resolved: person, ambiguous: false, candidates: [person] }); const result = await x.service.resolveFromSemantic({ actorUserId: 'a', dialogueScopeKey: 's', semanticTurn: { ...base, kind: 'write_request', objectiveType: 'send_message', independentObjective: 'yes', slots: { recipient: 'Lina' } }, dialogue }); expect(result.status).toBe('resolved'); });
    it('ignores model-proposed IDs and never makes a direct people query', async () => { const x = service({ resolved: null, ambiguous: false, candidates: [] }); const result = await x.service.resolveFromSemantic({ actorUserId: 'a', dialogueScopeKey: 's', semanticTurn: { ...base, slots: { personId: 'forged-id' }, entityHints: [] }, dialogue }); expect(result.status).toBe('not_applicable'); expect(x.resolve).not.toHaveBeenCalled(); });
    it('does not use raw utterance, LLM, disposition, mutation, authorization, or execution', async () => { const source = await import('../src/services/agentPersonResolution.service'); const text = await (await import('node:fs/promises')).readFile(new URL('../src/services/agentPersonResolution.service.ts', import.meta.url), 'utf8'); expect(text).not.toMatch(/rawUtterance|Llm|AgentTurnDispositionService|execute|\.from\(/); expect(source.agentPersonResolutionService).toBeDefined(); });
    it('passes actor and scope as context without allowing scope to override actor', async () => { const x = service({ resolved: null, ambiguous: false, candidates: [] }); await x.service.resolveFromSemantic({ actorUserId: 'actor-a', dialogueScopeKey: 'scope-b', semanticTurn: base, dialogue }); expect(x.resolve).toHaveBeenCalledWith('actor-a', { name: 'Lina' }); });
});
