import { describe, expect, it } from 'vitest';
import { CanonicalSemanticProducer } from '../src/services/canonicalSemanticProducer.service';
import { AgentTurnCommitService } from '../src/services/agentTurnCommit.service';
import type { NormalizedSemanticTurnV3 } from '../src/types/agentTurnCommit';

const base = { kind: 'write_request', domain: 'commitment', objectiveCompleteness: 'complete', lifecycleCommand: 'none', lifecycleTarget: 'unspecified', lifecycleEvidence: 'unknown', pendingSlotAnswer: 'not_a_slot_answer', continuationLike: 'unknown', candidateSlotType: null, independentObjective: 'yes', objectiveType: 'create_commitment', entityHints: [], slots: {}, ambiguityFields: [], confidence: .8 } as const;
class Fake { calls = 0; constructor(private result: unknown) {} async interpret() { this.calls++; return this.result; } }
const produce = (result: unknown) => { const model = new Fake(result); return { model, promise: new CanonicalSemanticProducer(model).produceV3({ text: 'x', modality: 'text' }) }; };

describe('M-7 SemanticTurn V3 structured temporal contract', () => {
    it('validates absolute date, 24h datetime, relative date, duration, and weekday', async () => { for (const temporalFact of [{ kind: 'absolute_date', precision: 'date', year: 2026, month: 9, day: 20 }, { kind: 'absolute_datetime', precision: 'minute', year: 2026, month: 9, day: 20, hour: 15, minute: 30, meridiem: '24h' }, { kind: 'relative_date', precision: 'date', amount: 1, unit: 'days' }, { kind: 'relative_duration', precision: 'duration', amount: 2, unit: 'hours' }, { kind: 'weekday', precision: 'date', weekday: 5, relation: 'next' }]) { const x = produce({ ...base, temporalFact }); expect((await x.promise).temporalFact).toEqual(temporalFact); expect(x.model.calls).toBe(1); } });
    it('represents ambiguous time without inventing meridiem', async () => { const x = produce({ ...base, temporalFact: { kind: 'time_only', precision: 'minute', hour: 8, minute: 0, meridiem: 'unknown', ambiguity: 'clock' } }); expect((await x.promise).temporalFact).toMatchObject({ meridiem: 'unknown', ambiguity: 'clock' }); });
    it('preserves date-only precision and emits no canonical timestamp/timezone', async () => { const x = await produce({ ...base, temporalFact: { kind: 'absolute_date', precision: 'date', year: 2026, month: 9, day: 20 } }).promise; expect(x.temporalFact).not.toHaveProperty('timezone'); expect(x).not.toHaveProperty('canonicalInstant'); expect(x.temporalFact).not.toHaveProperty('hour'); });
    it('rejects contradictory or malformed temporal facts conservatively', async () => { expect((await produce({ ...base, temporalFact: { kind: 'absolute_date', precision: 'minute', year: 2026, month: 2, day: 31 } }).promise).kind).toBe('unknown'); expect((await produce({ ...base, temporalFact: { kind: 'relative_duration', precision: 'duration', amount: -2, unit: 'hours' } }).promise).kind).toBe('unknown'); });
    it('allows V3 with no temporal fact and keeps ranges out', async () => { const result = await produce(base).promise; expect(result.temporalFact).toBeUndefined(); expect(JSON.stringify(result)).not.toMatch(/range/i); });
    it('uses trusted structured evidence with zero model calls', async () => { const model = new Fake(base); const result = await new CanonicalSemanticProducer(model).produceV3({ text: 'ignored', modality: 'text', authoritativeSemanticV3: { ...base, source: 'deterministic', temporalFact: { kind: 'relative_date', precision: 'date', amount: 1, unit: 'days' } } as Omit<NormalizedSemanticTurnV3, 'version'> }); expect(model.calls).toBe(0); expect(result.version).toBe(3); });
    it('malformed model output falls back to unknown with one call', async () => { const x = produce({ ...base, temporalFact: { kind: 'time_only', precision: 'minute', hour: 8, minute: 0, meridiem: 'pm', ambiguity: 'bad' } }); expect((await x.promise).kind).toBe('unknown'); expect(x.model.calls).toBe(1); });
    it('does not perform temporal NLP, disposition, authorization, or execution', async () => { const result = await produce({ ...base, temporalFact: { kind: 'time_only', precision: 'minute', hour: 8, minute: 0, meridiem: 'unknown', ambiguity: 'clock' } }).promise; expect(result).not.toHaveProperty('disposition'); expect(result).not.toHaveProperty('authorization'); });
    it('supports stable admitted reference metadata without changing semantic output', async () => { const admission = { createdAt: '2026-09-14T12:00:00.000Z', turnReferenceInstant: '2026-09-14T12:00:00.000Z' }; expect(admission.turnReferenceInstant).toBe(admission.createdAt); });
    it('V3 checkpoint save uses version 3 and preserves payload', async () => { const calls: any[] = []; const service = new AgentTurnCommitService({ rpc: async (_name: string, args: any) => { calls.push(args); return { data: { semantic_turn: args.p_semantic_turn }, error: null }; } }); const semantic = { version: 3, ...base, source: 'deterministic' as const, temporalFact: { kind: 'relative_duration' as const, precision: 'duration' as const, amount: 2, unit: 'hours' as const } }; const saved = await service.saveSemanticCheckpointV3({ turnId: 't', actorUserId: 'a', dialogueScopeKey: 's', turnSequence: 1, semanticTurn: semantic }); expect(calls[0].p_semantic_version).toBe(3); expect(saved).toEqual(semantic); });
});
