import { AppError } from '../utils/AppError';

// The client is served from the HTTPS staging origin. An inline WebView HTML
// document has an opaque/local origin on iOS, which is not a reliable secure
// context for getUserMedia. This asset contains no credentials; the mobile
// client injects the authenticated session configuration before startup.
const CLIENT_HTML = `<!doctype html>
<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>
body{margin:0;background:#091426;color:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,sans-serif;display:flex;min-height:100vh;align-items:center;justify-content:center}
main{text-align:center;padding:28px}.orb{width:112px;height:112px;border-radius:56px;background:#1677e8;box-shadow:0 0 0 14px rgba(22,119,232,.15);margin:0 auto 24px;display:flex;align-items:center;justify-content:center;font-size:44px}.orb.active{animation:pulse 1.5s infinite}.status{font-size:17px;font-weight:600;margin:8px 0}.hint{font-size:13px;color:#a9b7c9;line-height:1.5;max-width:290px;margin:0 auto}.stop{margin-top:28px;background:#ef4444;border:0;border-radius:22px;padding:12px 24px;color:white;font-size:16px;font-weight:700}@keyframes pulse{0%,100%{transform:scale(1)}50%{transform:scale(1.08)}}
</style></head><body><main><div id="orb" class="orb">&#9673;</div><div id="status" class="status">Conectando con Ping...</div><p id="hint" class="hint">Habla normalmente. Ping respondera por voz y conservara el mismo contexto.</p><button id="stop" class="stop" type="button">Terminar</button><audio id="remote" autoplay playsinline></audio></main><script>
(function(){
  const statusEl=document.getElementById('status'),hintEl=document.getElementById('hint'),orb=document.getElementById('orb'),remote=document.getElementById('remote');
  let cfg=null,pc=null,dc=null,mic=null,startedAt=0,firstAudioSent=false,assistantSpeaking=false,closed=false,providerSessionId=null;
  const id=()=>{try{return crypto.randomUUID()}catch{return 'm8-'+Date.now()+'-'+Math.random().toString(16).slice(2)}};
  const post=(message)=>{try{window.ReactNativeWebView&&window.ReactNativeWebView.postMessage(JSON.stringify(message))}catch{}};
  const telemetry=(event,extra={})=>{if(!cfg)return;const payload={voiceSessionId:cfg.voiceSessionId,deviceSessionId:cfg.deviceSessionId,event,atMs:Math.max(0,Date.now()-startedAt),sessionId:providerSessionId||undefined,...extra};post({type:'telemetry',payload});fetch(cfg.apiUrl+'/agent/voice/live/telemetry',{method:'POST',headers:{Authorization:cfg.authorization,'Content-Type':'application/json'},body:JSON.stringify(payload)}).catch(()=>{})};
  const setStatus=(text,hint,active=false)=>{statusEl.textContent=text;hintEl.textContent=hint||'';orb.className=active?'orb active':'orb'};
  const sendEvent=(value)=>{if(!dc||dc.readyState!=='open')throw new Error('voice_data_channel_unavailable');dc.send(JSON.stringify(value))};
  async function callCore(input,callId){const body={input,channel:'mobile',locale:cfg.locale,timezone:cfg.timezone,conversationId:cfg.conversationId};const response=await fetch(cfg.apiUrl+'/agent/turn',{method:'POST',headers:{Authorization:cfg.authorization,'Content-Type':'application/json','Idempotency-Key':id()},body:JSON.stringify(body)});const text=await response.text();let result=null;try{result=JSON.parse(text)}catch{}if(!response.ok)throw new Error('core_'+response.status);const core=result||{kind:'error',status:'unavailable'};const kind=core.kind==='plan'?'plan':core.kind==='clarification'?'clarification':core.kind==='response'?'response':'error';telemetry('core_disposition',{coreKind:kind,confirmationRequired:core.confirmationRequested===true,sideEffects:0});if(core.confirmationRequested===true)telemetry('confirmation_requested',{coreKind:'plan',confirmationRequired:true,sideEffects:0});sendEvent({type:'conversation.item.create',item:{type:'function_call_output',call_id:callId,output:JSON.stringify({core})}});sendEvent({type:'response.create'})}
  function onEvent(raw){let event;try{event=JSON.parse(raw.data||raw)}catch{return}if(event.type==='session.created'){providerSessionId=event.session?.id||providerSessionId;telemetry('session_connected',{sessionId:providerSessionId});setStatus('Ping esta escuchando','Habla cuando quieras.',true);return}if(event.type==='input_audio_buffer.speech_started'){if(assistantSpeaking){try{sendEvent({type:'response.cancel'})}catch{}telemetry('barge_in',{sideEffects:0});assistantSpeaking=false}telemetry('speech_started',{sideEffects:0});return}if(event.type==='input_audio_buffer.speech_stopped'){telemetry('speech_stopped',{sideEffects:0});return}if(event.type==='response.output_audio_transcript.delta'){if(!assistantSpeaking){assistantSpeaking=true;telemetry('assistant_audio_started',{sideEffects:0})}return}if(event.type==='response.output_audio.done'){assistantSpeaking=false;telemetry('assistant_audio_stopped',{sideEffects:0});return}if(event.type==='response.function_call_arguments.done'){let args;try{args=JSON.parse(event.arguments||'{}')}catch{telemetry('error',{detailCode:'invalid_tool_arguments',sideEffects:0});return}if(typeof args.input!=='string'||!args.input.trim()){telemetry('error',{detailCode:'missing_core_input',sideEffects:0});return}setStatus('Ping esta pensando','Consultando el mismo Ping Core...',true);callCore(args.input,event.call_id).catch(()=>{telemetry('fallback',{detailCode:'core_unavailable',sideEffects:0});setStatus('Ping no esta disponible','Puedes cerrar y volver a intentarlo.')});return}if(event.type==='session.closed'){closed=true;telemetry('session_closed',{sideEffects:0});setStatus('Conversacion terminada','');return}if(event.type==='error'){telemetry('error',{detailCode:'provider_event',sideEffects:0});setStatus('No se pudo iniciar la voz','Cierra esta ventana y usa el modo de texto.')}}
  async function start(){startedAt=Date.now();telemetry('session_setup_started',{sideEffects:0});try{if(!cfg||!navigator.mediaDevices?.getUserMedia||typeof RTCPeerConnection!=='function')throw new Error('webrtc_unavailable');mic=await navigator.mediaDevices.getUserMedia({audio:true});pc=new RTCPeerConnection();pc.ontrack=(event)=>{remote.srcObject=event.streams[0];remote.play().catch(()=>{})};remote.onplaying=()=>{if(!firstAudioSent){firstAudioSent=true;telemetry('first_useful_audio',{sideEffects:0})}};mic.getTracks().forEach(track=>pc.addTrack(track,mic));dc=pc.createDataChannel('oai-events');dc.onmessage=onEvent;const offer=await pc.createOffer();await pc.setLocalDescription(offer);const response=await fetch(cfg.apiUrl+'/agent/voice/live/session',{method:'POST',headers:{Authorization:cfg.authorization,'Content-Type':'application/json'},body:JSON.stringify({sdp:offer.sdp,voiceSessionId:cfg.voiceSessionId,deviceSessionId:cfg.deviceSessionId,conversationId:cfg.conversationId,locale:cfg.locale,timezone:cfg.timezone})});const result=await response.json();if(!response.ok)throw new Error(result.error||'live_session_failed');providerSessionId=result.sessionId;await pc.setRemoteDescription({type:'answer',sdp:result.sdp})}catch(error){telemetry('error',{detailCode:error&&error.message?String(error.message).slice(0,80):'session_failed',sideEffects:0});setStatus('No se pudo iniciar la voz','El modo de texto sigue disponible.');post({type:'error'})}}
  function stop(){if(closed)return;try{if(dc&&dc.readyState==='open')dc.send(JSON.stringify({type:'session.close'}))}catch{}if(mic)mic.getTracks().forEach(t=>t.stop());if(pc)pc.close();closed=true;telemetry('session_closed',{sideEffects:0});post({type:'closed'})}
  document.getElementById('stop').addEventListener('click',stop);window.addEventListener('beforeunload',stop);setTimeout(()=>{if(window.__PING_CONFIG){cfg=window.__PING_CONFIG;start()}else{setStatus('No se pudo configurar la voz','Cierra esta ventana y vuelve a intentarlo.');post({type:'error'})}},200)
})();
</script></body></html>`;

export function getM8LiveVoiceClientHtml(): string {
    if (process.env.PING_ENVIRONMENT !== 'staging' || process.env.M8_LIVE_VOICE_ENABLED !== 'true') {
        throw new AppError('Live voice is not enabled in this environment', 404);
    }
    return CLIENT_HTML;
}
