import { AppError } from '../utils/AppError';
import { M8_VOICE_PROTOCOL_VERSION } from './m8VoiceBootstrapProtocol';

// Credential-free WebView client served by the HTTPS staging origin. The
// native shell injects the authenticated session envelope; this document
// never contains a provider key, SDP in telemetry, or raw conversation text.
// The bootstrap is a bounded, idempotent protocol: every wait has a timeout,
// configuration can be requested repeatedly, and every terminal error is
// recoverable through an explicit retry instead of an infinite spinner.
const CLIENT_HTML = `<!doctype html>
<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>
body{margin:0;background:#091426;color:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,sans-serif;display:flex;min-height:100vh;align-items:center;justify-content:center}
main{text-align:center;padding:28px}.orb{width:112px;height:112px;border-radius:56px;background:#1677e8;box-shadow:0 0 0 14px rgba(22,119,232,.15);margin:0 auto 24px;display:flex;align-items:center;justify-content:center;font-size:44px}.orb.active{animation:pulse 1.5s infinite}.status{font-size:17px;font-weight:600;margin:8px 0}.hint{font-size:13px;color:#a9b7c9;line-height:1.5;max-width:290px;margin:0 auto}.stop,.retry{margin-top:28px;border:0;border-radius:22px;padding:12px 24px;color:white;font-size:16px;font-weight:700}.stop{background:#ef4444}.retry{background:#1677e8;margin-left:8px}@keyframes pulse{0%,100%{transform:scale(1)}50%{transform:scale(1.08)}}
</style></head><body><main><div id="orb" class="orb">&#9673;</div><div id="status" class="status">Preparando Ping...</div><p id="hint" class="hint">Configurando la conversación segura.</p><button id="stop" class="stop" type="button">Terminar</button><button id="retry" class="retry" type="button" hidden>Reintentar</button><audio id="remote" autoplay playsinline muted></audio></main><script nonce="__M8_SCRIPT_NONCE__">
(function(){
  const statusEl=document.getElementById('status'),hintEl=document.getElementById('hint'),orb=document.getElementById('orb'),remote=document.getElementById('remote'),retryEl=document.getElementById('retry');
  const CONFIG_PROTOCOL=${M8_VOICE_PROTOCOL_VERSION}, CONFIG_ATTEMPTS=12, CONFIG_INTERVAL=500;
  let cfg=null,pc=null,dc=null,mic=null,startedAt=Date.now(),firstAudioSent=false,assistantSpeaking=false,outputPlaybackPending=false,pendingPlaybackInterruption=false,coreResultReady=false,responseActive=false,responseHasAudio=false,responseProviderId=null,responseTurnId=null,responseOutputText='',responseAudioDeltaCount=0,coreTurnInFlight=false,closed=false,failed=false,currentStage='bootstrap',providerSessionId=null,providerSessionCreated=false,configAttempts=0,reconnectAttempts=0,configTimer=null,sessionTimer=null,disconnectTimer=null,resolveSessionCreated=null,rejectSessionCreated=null,activeTurnId=null,turnSequence=0,responseCreateCount=0,audioResponseCount=0,lastVadState='idle',lastWebrtcState='new',lastIceState='new',lastAudioState='idle';
  const id=()=>{try{return crypto.randomUUID()}catch{return 'm8-'+Date.now()+'-'+Math.random().toString(16).slice(2)}};
  const post=(message)=>{try{window.ReactNativeWebView&&window.ReactNativeWebView.postMessage(JSON.stringify(message))}catch{}};
  const setStatus=(text,hint,active=false)=>{statusEl.textContent=text;hintEl.textContent=hint||'';orb.className=active?'orb active':'orb'};
  const safeText=(value,max)=>typeof value==='string'?value.replace(/Bearer\\s+[^\\s]+/ig,'Bearer [redacted]').replace(/https?:\\/\\/[^\\s]+/ig,'[url redacted]').replace(/(api[_-]?key|access[_-]?token|refresh[_-]?token|authorization|password|secret)\\s*[:=]\\s*[^\\s,;]+/ig,'$1=[redacted]').slice(0,max):undefined;
  const telemetry=(event,extra={})=>{if(!cfg)return;const payload={voiceSessionId:cfg.voiceSessionId,deviceSessionId:cfg.deviceSessionId,event,atMs:Math.max(0,Date.now()-startedAt),sessionId:providerSessionId||undefined,providerResponseId:responseProviderId||undefined,turnId:activeTurnId||responseTurnId||undefined,turnSequence,responseCreateCount,audioResponseCount,assistantSpeaking,coreResultReady,vadState:lastVadState,webrtcState:lastWebrtcState,iceState:lastIceState,audioState:lastAudioState,conversationPresent:typeof cfg.conversationId==='string',...extra};post({type:'telemetry',payload});fetch(cfg.apiUrl+'/agent/voice/live/telemetry',{method:'POST',headers:{Authorization:cfg.authorization,'Content-Type':'application/json'},body:JSON.stringify(payload),keepalive:event==='session_closed'}).catch(()=>{})};
  const stage=(name,text,hint,extra={})=>{currentStage=name;setStatus(text,hint,name==='session_connected'||name==='webrtc_connected'||name==='data_channel_ready'||name==='listening');post({type:'stage',stage:name});telemetry('voice_stage',{stage:name,...extra})};
  const errorDetails=(error)=>{const value=error||{};const name=typeof value.name==='string'?value.name.slice(0,60):'Error';const code=typeof value.code==='string'||typeof value.code==='number'?String(value.code).slice(0,60):undefined;const message=typeof value.message==='string'?value.message.replace(/Bearer\\s+[^\\s]+/ig,'Bearer [redacted]').replace(/https?:\\/\\/[^\\s]+/ig,'[url redacted]').slice(0,120):'voice_session_failed';return {errorName:name,errorCode:code,errorMessage:message}};
  const withTimeout=(promise,ms,code)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(code)),ms);promise.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})});
  const sendEvent=(value)=>{if(!dc||dc.readyState!=='open')throw new Error('voice_data_channel_unavailable');dc.send(JSON.stringify(value))};
  const normalizeSdp=(value)=>{const crlf=String.fromCharCode(13,10),lf=String.fromCharCode(10),cr=String.fromCharCode(13);const lines=String(value).replaceAll(crlf,lf).replaceAll(cr,lf).split(lf);while(lines.length&&lines[lines.length-1]==='')lines.pop();return lines.join(crlf)+crlf};
  const validConfig=(value)=>Boolean(value&&typeof value.apiUrl==='string'&&typeof value.authorization==='string'&&value.authorization.length>0&&typeof value.voiceSessionId==='string'&&typeof value.deviceSessionId==='string'&&(!value.protocolVersion||value.protocolVersion===CONFIG_PROTOCOL));
  const acceptConfig=()=>{const next=window.__PING_CONFIG;if(!validConfig(next)||cfg)return false;cfg=next;startedAt=Date.now();post({type:'config_ack',protocolVersion:CONFIG_PROTOCOL,handshakeId:cfg.handshakeId});stage('config_received','Configuración lista','Validando la sesión del usuario.');stage('config_acknowledged','Configuración confirmada','Preparando autenticación de voz.');stage('auth_ready','Autenticación lista','Solicitando acceso al micrófono.');return true};
  const requestConfig=()=>{configAttempts+=1;post({type:'config_requested',protocolVersion:CONFIG_PROTOCOL,handshakeId:window.__PING_CONFIG?.handshakeId,attempt:configAttempts});stage('config_requested','Preparando Ping','Solicitando configuración segura.',{attempt:configAttempts})};
  async function waitForConfig(){
    stage('webview_ready','Preparando Ping','Iniciando el canal seguro.');
    window.addEventListener('ping-config',acceptConfig);
    if(acceptConfig())return;
    for(let attempt=0;attempt<CONFIG_ATTEMPTS&&!cfg;attempt+=1){requestConfig();await new Promise(resolve=>setTimeout(resolve,CONFIG_INTERVAL));acceptConfig()}
    window.removeEventListener('ping-config',acceptConfig);
    if(!cfg)throw new Error('voice_config_timeout');
  }
  const waitForDataChannel=()=>new Promise((resolve,reject)=>{if(dc?.readyState==='open'){stage('data_channel_ready','Canal de control listo','Esperando a Ping.');resolve(true);return}const timer=setTimeout(()=>reject(new Error('data_channel_timeout')),15000);const previous=dc?.onopen;if(dc)dc.onopen=()=>{if(previous)previous.call(dc);clearTimeout(timer);stage('data_channel_ready','Canal de control listo','Esperando a Ping.');resolve(true)}});
  const waitForSessionCreated=()=>new Promise((resolve,reject)=>{if(providerSessionCreated){resolve(true);return}resolveSessionCreated=resolve;rejectSessionCreated=reject;sessionTimer=setTimeout(()=>{rejectSessionCreated=null;resolveSessionCreated=null;reject(new Error('provider_session_timeout'))},20000)});
  const waitForIceGathering=()=>new Promise(resolve=>{if(!pc||pc.iceGatheringState==='complete'){resolve(true);return}const timer=setTimeout(()=>{if(pc)pc.onicegatheringstatechange=null;resolve(true)},10000);pc.onicegatheringstatechange=()=>{if(pc?.iceGatheringState==='complete'){clearTimeout(timer);pc.onicegatheringstatechange=null;resolve(true)}}});
  const clearPending=()=>{if(configTimer)clearTimeout(configTimer);if(sessionTimer)clearTimeout(sessionTimer);if(disconnectTimer)clearTimeout(disconnectTimer);configTimer=null;sessionTimer=null;disconnectTimer=null;resolveSessionCreated=null;rejectSessionCreated=null};
  function fail(stageName,error,httpStatus){if(failed||closed)return;failed=true;clearPending();const details=errorDetails(error);const failedStage=stageName||currentStage||'unknown';telemetry('error',{detailCode:failedStage,httpStatus,...details,sideEffects:0});post({type:'m8_diagnostic_error',stage:failedStage,details});retryEl.hidden=false;setStatus('No se pudo iniciar la voz','Falló la etapa '+failedStage+'. '+(details.errorCode||details.errorMessage||'Revisa la conexión e inténtalo nuevamente.'),false);}
  const setAudioGate=(enabled)=>{coreResultReady=enabled;remote.muted=!enabled;if(enabled)remote.play().catch(()=>{})};
  const coreSummary=(core)=>{const answer=core?.answer||core?.response?.answer||core?.presentation?.summary||core?.presentation?.headline||core?.reason;return safeText(typeof answer==='string'?answer:'',800)};
  const cancelResponse=(cause)=>{if(!responseActive){telemetry('response_cancel',{cancelCause:cause,detailCode:'response_cancel_skipped_no_active_response',sideEffects:0});return false}try{responseActive=false;telemetry('response_cancel',{cancelCause:cause,detailCode:'response_cancel_sent',sideEffects:0});sendEvent({type:'response.cancel'});return true}catch(error){telemetry('error',{detailCode:'response_cancel_failed',cancelCause:cause,...errorDetails(error),sideEffects:0});return false}};
  const completeAssistantResponse=(detailCode)=>{const wasSpeaking=assistantSpeaking||lastAudioState==='playing';const shouldReturnToListening=responseHasAudio||wasSpeaking||lastAudioState==='playing';outputPlaybackPending=shouldReturnToListening;pendingPlaybackInterruption=false;assistantSpeaking=false;responseActive=false;lastAudioState='provider_done';telemetry('voice_stage',{stage:'provider_audio_generation_done',detailCode,responseHasAudio,realtimeOutputText:responseOutputText||undefined,audioDeltaCount:responseAudioDeltaCount,sideEffects:0});if(shouldReturnToListening&&!closed&&!failed&&currentStage!=='listening')stage('listening','Ping está listo','Habla cuando quieras.',{detailCode,sideEffects:0});responseHasAudio=false;responseProviderId=null;responseTurnId=null;responseOutputText='';responseAudioDeltaCount=0};
  const createResponse=(cause,toolChoice)=>{responseActive=true;responseHasAudio=toolChoice!=='required';responseProviderId=null;responseTurnId=activeTurnId;responseOutputText='';responseAudioDeltaCount=0;responseCreateCount+=1;telemetry('response_create',{detailCode:cause,responseCreateCount,responseHasAudio,sideEffects:0});sendEvent(toolChoice?{type:'response.create',response:{tool_choice:toolChoice,output_modalities:toolChoice==='required'?['text']:['audio']}}:{type:'response.create'})};
  async function callCore(input,callId,turnId){
    outputPlaybackPending=false;pendingPlaybackInterruption=false;setAudioGate(false);
    const coreStartedAt=Date.now();
    telemetry('core_request_started',{turnId:turnId||activeTurnId,transcript:safeText(input,500),detailCode:'agent_turn_started',sideEffects:0});
    stage('core_request_started','Ping está pensando','Consultando el mismo Ping Core.',{sideEffects:0});
    const body={input,channel:'mobile',locale:cfg.locale,timezone:cfg.timezone,conversationId:cfg.conversationId};
    const response=await withTimeout(fetch(cfg.apiUrl+'/agent/turn',{method:'POST',headers:{Authorization:cfg.authorization,'Content-Type':'application/json','Idempotency-Key':id()},body:JSON.stringify(body)}),20000,'core_request_timeout');
    const text=await response.text();let result=null;try{result=JSON.parse(text)}catch{}
    stage('core_response_received',response.ok?'Respuesta recibida':'Core no disponible','Preparando la respuesta de voz.',{httpStatus:response.status,sideEffects:0});
    if(!response.ok)throw new Error('core_'+response.status);
    const core=result||{kind:'error',status:'unavailable'};const kind=core.kind==='plan'?'plan':core.kind==='clarification'?'clarification':core.kind==='response'?'response':'error';
    telemetry('core_disposition',{turnId:turnId||activeTurnId,coreKind:kind,coreAnswer:coreSummary(core),confirmationRequired:core.confirmationRequested===true,httpStatus:response.status,detailCode:'agent_turn_completed',sideEffects:0});
    telemetry('core_response_received',{turnId:turnId||activeTurnId,httpStatus:response.status,latencyMs:Date.now()-coreStartedAt,detailCode:'agent_turn_completed',sideEffects:0});
    if(core.confirmationRequested===true)telemetry('confirmation_requested',{coreKind:'plan',confirmationRequired:true,sideEffects:0});
    sendEvent({type:'conversation.item.create',item:{type:'function_call_output',call_id:callId,output:JSON.stringify({core})}});telemetry('function_call_output',{turnId:turnId||activeTurnId,detailCode:'ping_core_turn_output',coreKind:kind,coreAnswer:coreSummary(core),sideEffects:0});createResponse('core_result_authorized','none');setAudioGate(true);
  }
  function onEvent(raw){
    let event;try{event=JSON.parse(raw.data||raw)}catch{telemetry('error',{detailCode:'provider_event_invalid_json',sideEffects:0});return}
    if(event.type==='response.created'){responseProviderId=event.response?.id||event.response_id||null;telemetry('voice_stage',{stage:'response_created',detailCode:'provider_response_created',providerEventType:event.type,sideEffects:0})}
    const isOutputTextDelta=event.type==='response.output_text.delta'||event.type==='response.audio_transcript.delta'||event.type==='response.output_audio_transcript.delta';
    const isOutputAudioDelta=event.type==='response.audio.delta'||event.type==='response.output_audio.delta';
    if(isOutputTextDelta){const delta=event.delta||event.text||'';if(typeof delta==='string'&&delta)responseOutputText=safeText((responseOutputText+delta).slice(0,800),800)||responseOutputText}
    if(isOutputAudioDelta)responseAudioDeltaCount+=1;
    if(event.type==='response.output_text.done'||event.type==='response.audio_transcript.done'||event.type==='response.output_audio_transcript.done'){responseOutputText=safeText(event.transcript||event.text||responseOutputText,800)||responseOutputText;telemetry('voice_stage',{stage:'realtime_output_transcript_done',detailCode:event.type,providerEventType:event.type,realtimeOutputText:responseOutputText||undefined,sideEffects:0})}
    if(event.type==='response.audio.done'||event.type==='response.output_audio.done')telemetry('voice_stage',{stage:'realtime_audio_done',detailCode:event.type,providerEventType:event.type,audioDeltaCount:responseAudioDeltaCount,realtimeOutputText:responseOutputText||undefined,sideEffects:0});
    if(event.type==='response.output_audio_transcript.delta'||event.type==='response.output_audio.delta'){if(!coreResultReady){telemetry('error',{detailCode:'audio_before_core_result',sideEffects:0});return}}
    if(event.type==='response.output_audio.done'||event.type==='response.audio.done')completeAssistantResponse('audio_output_done');
    if(event.type==='response.done'||event.type==='response.completed'){if(responseHasAudio||assistantSpeaking||lastAudioState==='playing')completeAssistantResponse(event.type);else{responseActive=false;telemetry('voice_stage',{stage:'response_done',detailCode:'tool_response_done',providerEventType:event.type,realtimeOutputText:responseOutputText||undefined,audioDeltaCount:responseAudioDeltaCount,sideEffects:0})}}
    if(event.type==='response.function_call_arguments.done'&&assistantSpeaking&&responseActive)cancelResponse('function_call_before_core_result');
    if(event.type==='conversation.item.input_audio_transcription.completed'||event.type==='input_audio_transcription.completed'){telemetry('transcript_received',{transcript:safeText(event.transcript||event.text,500),detailCode:'input_transcription_completed',sideEffects:0});return}
    if(event.type==='input_audio_buffer.speech_started'){const wasAssistantSpeaking=assistantSpeaking;const wasOutputPending=outputPlaybackPending&&!wasAssistantSpeaking;lastVadState='speech_started';pendingPlaybackInterruption=wasOutputPending;if(wasAssistantSpeaking){cancelResponse('speech_started_while_assistant_speaking');setAudioGate(false);outputPlaybackPending=false;pendingPlaybackInterruption=false;telemetry('barge_in',{cancelCause:'speech_started_while_assistant_speaking',selfAudioCaptureSuspected:coreResultReady,vadState:lastVadState,sideEffects:0});stage('barge_in_detected','Ping te escucha','Interrumpiendo la respuesta anterior.',{sideEffects:0});assistantSpeaking=false}if(!activeTurnId){activeTurnId=id();turnSequence+=1}}
    if(event.type==='input_audio_buffer.speech_stopped'){lastVadState='speech_stopped';if(activeTurnId&&!assistantSpeaking&&!responseActive&&!coreTurnInFlight){createResponse('user_turn_ready','required')}return}
    if((event.type==='response.output_audio_transcript.delta'||event.type==='response.output_audio.delta'||event.type==='response.audio.delta')&&coreResultReady&&!assistantSpeaking){audioResponseCount+=1;lastAudioState='playing'}
    if(event.type==='session.created'){providerSessionCreated=true;providerSessionId=event.session?.id||providerSessionId;if(sessionTimer)clearTimeout(sessionTimer);if(resolveSessionCreated)resolveSessionCreated(true);resolveSessionCreated=null;rejectSessionCreated=null;telemetry('session_connected',{sessionId:providerSessionId});stage('session_connected','Ping está escuchando','Habla cuando quieras.');stage('listening','Ping está listo','Habla cuando quieras.');return}
    if(event.type==='input_audio_buffer.speech_started'){telemetry('speech_started',{selfAudioCaptureSuspected:false,vadState:lastVadState,sideEffects:0});return}
    if(event.type==='input_audio_buffer.speech_stopped'){telemetry('speech_stopped',{sideEffects:0});return}
    if(event.type==='response.output_audio_transcript.delta'||event.type==='response.output_audio.delta'){if(!assistantSpeaking){assistantSpeaking=true;telemetry('assistant_audio_started',{sideEffects:0});stage('audio_output_started','Ping está respondiendo','Puedes interrumpirlo cuando quieras.',{sideEffects:0})}return}
    if(event.type==='response.output_audio.done'||event.type==='response.audio.done'){return}
    if(event.type==='response.function_call_arguments.done'){let args;try{args=JSON.parse(event.arguments||'{}')}catch{telemetry('error',{detailCode:'invalid_tool_arguments',sideEffects:0});return}if(typeof args.input!=='string'||!args.input.trim()){telemetry('error',{detailCode:'missing_core_input',sideEffects:0});return}const normalizedInput=args.input.trim().toLowerCase();if(normalizedInput==='[inaudible noise]'){telemetry('input_ignored',{detailCode:pendingPlaybackInterruption?'self_audio_echo_suspected':'inaudible_input',selfAudioCaptureSuspected:pendingPlaybackInterruption,sideEffects:0});activeTurnId=null;pendingPlaybackInterruption=false;return}if(coreTurnInFlight){telemetry('input_ignored',{detailCode:'core_turn_already_in_flight',sideEffects:0});return}if(pendingPlaybackInterruption){setAudioGate(false);outputPlaybackPending=false;pendingPlaybackInterruption=false;telemetry('voice_stage',{stage:'confirmed_user_turn_after_pending_output',detailCode:'playback_gate_released_for_core',sideEffects:0})}coreTurnInFlight=true;callCore(args.input,event.call_id,activeTurnId).catch(error=>fail('core_request',error)).finally(()=>{coreTurnInFlight=false;activeTurnId=null;pendingPlaybackInterruption=false});return}
    if(event.type==='session.closed'){closed=true;clearPending();telemetry('session_closed',{sideEffects:0});setStatus('Conversación terminada','');return}
    if(event.type==='response.cancelled'||event.type==='response.canceled'){telemetry('response_cancel',{cancelCause:'provider_cancelled',detailCode:event.type,sideEffects:0});return}
    if(event.type==='error'){const providerError=event.error||event;const providerMessage=safeText(providerError.message||providerError.code||'provider_event_error',120);telemetry('error',{detailCode:'provider_event_error',errorName:safeText(providerError.type||providerError.name,60),errorCode:safeText(providerError.code,60),errorMessage:providerMessage,sideEffects:0});fail('provider_event',new Error(providerMessage||'provider_event_error'));}
  }
  async function start(){
    try{
      await waitForConfig();
      if(!navigator.mediaDevices?.getUserMedia||typeof RTCPeerConnection!=='function')throw new Error('webrtc_unavailable');
      stage('permission_request','Solicitando micrófono','Acepta el permiso para hablar con Ping.');
      mic=await withTimeout(navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}}),15000,'microphone_permission_timeout');
      stage('permission_granted','Micrófono listo','Preparando conexión de voz.');
      pc=new RTCPeerConnection();lastWebrtcState=pc.connectionState||'new';lastIceState=pc.iceConnectionState||'new';telemetry('audio_transport',{detailCode:'peer_connection_created',webrtcState:lastWebrtcState,iceState:lastIceState,sideEffects:0});
      pc.ontrack=(event)=>{stage('audio_ready','Audio de Ping listo','La conversación puede continuar.');remote.srcObject=event.streams[0];remote.play().catch(()=>{})};
       pc.onconnectionstatechange=()=>{const state=pc.connectionState;if(state==='connected'){if(disconnectTimer)clearTimeout(disconnectTimer);disconnectTimer=null;stage('webrtc_connected','Canal de voz conectado','Ping está listo.');}else if(state==='failed'||state==='closed')fail('webrtc_'+state,new Error('webrtc_'+state));else if(state==='disconnected'){stage('webrtc_disconnected','Conexión interrumpida','Intentando recuperar la conversación.');telemetry('error',{detailCode:'webrtc_disconnected',sideEffects:0});if(!disconnectTimer)disconnectTimer=setTimeout(()=>{if(reconnectAttempts<1&&!closed){reconnectAttempts+=1;telemetry('reconnect_attempt',{sideEffects:0});post({type:'retry'})}else fail('webrtc_disconnected',new Error('webrtc_reconnect_exhausted'))},5000)}};
       pc.oniceconnectionstatechange=()=>{lastIceState=pc.iceConnectionState;telemetry('audio_transport',{detailCode:'ice_state_changed',iceState:lastIceState,sideEffects:0});if(pc.iceConnectionState==='failed')fail('ice_failed',new Error('ice_failed'))};
       pc.addEventListener('connectionstatechange',()=>{lastWebrtcState=pc.connectionState;telemetry('audio_transport',{detailCode:'connection_state_changed',webrtcState:lastWebrtcState,sideEffects:0})});
       pc.addEventListener('track',event=>{lastAudioState='track_received';telemetry('audio_transport',{detailCode:'remote_track_received',audioState:lastAudioState,sideEffects:0});const track=event.streams?.[0]?.getAudioTracks?.()[0];if(track){track.addEventListener('mute',()=>{lastAudioState='track_muted';telemetry('audio_transport',{detailCode:'remote_track_muted',audioState:lastAudioState,sideEffects:0})});track.addEventListener('unmute',()=>{lastAudioState='track_unmuted';telemetry('audio_transport',{detailCode:'remote_track_unmuted',audioState:lastAudioState,sideEffects:0})});track.addEventListener('ended',()=>{lastAudioState='track_ended';telemetry('audio_transport',{detailCode:'remote_track_ended',audioState:lastAudioState,sideEffects:0})})}});
       remote.addEventListener('stalled',()=>{lastAudioState='stalled';telemetry('audio_transport',{detailCode:'remote_audio_stalled',audioState:lastAudioState,sideEffects:0})});remote.addEventListener('pause',()=>{lastAudioState='paused';telemetry('audio_transport',{detailCode:'remote_audio_paused',audioState:lastAudioState,sideEffects:0})});remote.addEventListener('ended',()=>{lastAudioState='ended';telemetry('audio_transport',{detailCode:'remote_audio_ended',audioState:lastAudioState,sideEffects:0})});remote.addEventListener('error',()=>{lastAudioState='error';telemetry('audio_transport',{detailCode:'remote_audio_error',audioState:lastAudioState,sideEffects:0})});
      remote.onplaying=()=>{if(!firstAudioSent){firstAudioSent=true;telemetry('first_useful_audio',{sideEffects:0})}};
      mic.getTracks().forEach(track=>pc.addTrack(track,mic));stage('peer_created','Preparando conexión de voz','Creando oferta segura.');
      dc=pc.createDataChannel('oai-events');dc.onmessage=onEvent;dc.onopen=()=>{telemetry('audio_transport',{detailCode:'data_channel_open',sideEffects:0})};dc.onclose=()=>{telemetry('audio_transport',{detailCode:'data_channel_closed',sideEffects:0})};dc.onerror=()=>{telemetry('error',{detailCode:'data_channel_error',sideEffects:0});fail('data_channel_error',new Error('data_channel_error'))};
      const offer=await withTimeout(pc.createOffer(),10000,'offer_timeout');stage('offer_created','Oferta creada','Negociando la sesión.');await withTimeout(pc.setLocalDescription(offer),10000,'local_description_timeout');stage('ice_gathering','Preparando red de voz','Esperando los candidatos de conexión.');await waitForIceGathering();const negotiatedSdp=pc.localDescription?.sdp;if(!negotiatedSdp)throw new Error('local_description_missing_after_ice');stage('rtc_negotiating','Negociando sesión','Contactando al backend de staging.');
      stage('voice_session_requested','Autenticando voz','Abriendo sesión segura en staging.');
      const response=await withTimeout(fetch(cfg.apiUrl+'/agent/voice/live/session',{method:'POST',headers:{Authorization:cfg.authorization,'Content-Type':'application/json'},body:JSON.stringify({sdp:negotiatedSdp,voiceSessionId:cfg.voiceSessionId,deviceSessionId:cfg.deviceSessionId,conversationId:cfg.conversationId,locale:cfg.locale,timezone:cfg.timezone})}),20000,'session_request_timeout');
      stage('voice_session_received',response.ok?'Sesión aceptada':'Sesión rechazada','Finalizando conexión.',{httpStatus:response.status});
      const body=await response.text();let result=null;try{result=JSON.parse(body)}catch{}
      if(!response.ok){const diagnostic=result?.diagnostic||{};const responseHint=typeof body==='string'?body.replace(/Bearer\\s+[^\\s]+/ig,'Bearer [redacted]').replace(/https?:\\/\\/[^\\s]+/ig,'[url redacted]').replace(/(api[_-]?key|access[_-]?token|refresh[_-]?token|authorization|password|secret)\\s*[:=]\\s*[^\\s,;]+/ig,'$1=[redacted]').slice(0,160):'';throw Object.assign(new Error(diagnostic.providerErrorMessage||result?.error||responseHint||'live_session_failed'),{httpStatus:diagnostic.httpStatus||response.status,code:diagnostic.errorCode||diagnostic.providerErrorType||'http_'+response.status})}
      if(!result?.sdp||!result?.sessionId)throw new Error('live_session_incomplete');
       providerSessionId=result.sessionId;const answerSdp=normalizeSdp(result.sdp);stage('remote_description_applying','Aplicando respuesta de voz','Completando la conexión segura.');try{await withTimeout(pc.setRemoteDescription({type:'answer',sdp:answerSdp}),15000,'remote_description_timeout')}catch(error){throw Object.assign(new Error('remote_description_invalid_sdp'),{cause:error})}stage('remote_description_set','Sesión de voz lista','Esperando confirmación del canal.');
      await waitForDataChannel();await waitForSessionCreated();
    }catch(error){fail(currentStage,error,error?.httpStatus)}
  }
  function stop(){if(closed)return;try{if(dc&&dc.readyState==='open')dc.send(JSON.stringify({type:'session.close'}))}catch{}if(mic)mic.getTracks().forEach(t=>t.stop());if(pc)pc.close();closed=true;clearPending();if(cfg)telemetry('session_closed',{sideEffects:0});post({type:'closed'})}
  document.getElementById('stop').addEventListener('click',stop);retryEl.addEventListener('click',()=>{post({type:'retry'});if(!window.ReactNativeWebView)location.reload()});window.addEventListener('beforeunload',stop);post({type:'webview_ready',protocolVersion:CONFIG_PROTOCOL});void start();
})();
</script></body></html>`;

export function getM8LiveVoiceClientHtml(scriptNonce = 'm8-test-nonce'): string {
    if (process.env.PING_ENVIRONMENT !== 'staging') {
        throw new AppError('Live voice is not enabled in this environment', 404);
    }
    return CLIENT_HTML.replace('__M8_SCRIPT_NONCE__', scriptNonce);
}
