-- M-7: the routing-mode admission RPC is backend-private and must not be
-- exposed through PostgREST. The private PostgreSQL adapter is the only
-- admission transport; service_role remains the migration-defined grant.
-- Intentionally no-op: no schema-cache reload is needed for an HTTP grant.
